Augmentation Modifier Description Rework
danielyxie/bitburner pull request #1028
Opened 2021-07-03 15:08 UTC by Kwazygloo

Augmentation descriptions are consistent with their assigned multipliers. 

Removed all references to "the player's".

Cleaned up wording and condensed sentence structure as appropriate.

Augmentation descriptions were changed based on the following rules:

hacking_mult: "Increases Hacking by number%."
strength_mult: "Increases Strength by number%."
defense_mult: "Increases Defense by number%."
dexterity_mult: "Increases Dexterity by number%."
agility_mult: "Increases Agility by number%."
charisma_mult: "Increases Charisma by number%."

hacking_exp_mult: "Increases Hacking experience gain by number%."
strength_exp_mult: "Increases Strength experience gain by number%."
defense_exp_mult: "Increases Defense experience gain by number%."
dexterity_exp_mult: "Increases Dexterity experience gain by number%."
agility_exp_mult: "Increases Agility experience gain by number%."
charisma_exp_mult: "Increases Charisma experience gain by number%."

hacking_chance_mult: "Increases Hacking success chance by number%."
hacking_speed_mult:  "Increases Hacking speed by number%."
hacking_money_mult: "Increases money gained from Hacking by number%."
hacking_grow_mult: "Improves grow() by number%."

faction_rep_mult: "Increases reputation gain from factions by number%."
company_rep_mult: "Increases reputation gain from companies by number%."

crime_money_mult: "Increases money gained from committing crimes by number%."
crime_success_mult: "Increases crime success rate by number%."
work_money_mult: "Increases money gained from working by number%."

hacknet_node_money_mult: "Increases money produced from Hacknet Nodes by number%."
hacknet_node_purchase_cost_mult: "Decreases the purchase cost of Hacknet Nodes by number%."
hacknet_node_level_cost_mult:  "Decreases the upgrade cost of Hacknet Nodes by number%.",

bladeburner_max_stamina_mult: "Increases Bladeburner Stamina by number%."
bladeburner_stamina_gain_mult: "Increases Bladeburner Stamina gain by number%."
bladeburner_analysis_mult: "Increases Bladeburner Field Analysis effectiveness by number%."
bladeburner_success_chance_mult: "Increases success chance in Bladeburner Contracts and Operations by number%."

// If an augment provides the same % bonus to all multipliers in any group

[
hacking_mult:
strength_mult:
defense_mult:
dexterity_mult:
agility_mult:
charisma_mult:
]

"Increases all stats by number%."

[
hacking_exp_mult:
strength_exp_mult:
defense_exp_mult:
dexterity_exp_mult:
agility_exp_mult:
charisma_exp_mult:
]

"Increases experience gain for all stats by number%."

[
strength_mult:
defense_mult:
dexterity_mult:
agility_mult:
]

"Increases all combat stats by number%."

[
strength_exp_mult:
defense_exp_mult:
dexterity_exp_mult:
agility_exp_mult:
]

"Increases experience gain for all combat stats by number%."

[
faction_rep_mult:
company_rep_mult:
]

"Increases reputation gain from factions and companies by number%."

// Unique

BladesSimulacrum:

"Allows the simultaneous performance of Bladeburner actions and other actions."

CashRoot:

"Provides {Money(1e6)} after a reset."
"Provides BruteSSH.exe after a reset."

Neurolink:

"Provides FTPCrack.exe and relaySMTP.exe after a reset."

NeuroFluxGovernor:

"Each level increases all multipliers by 1%."

2021-07-03 15:26 UTC, MageKing17 commented
It seems to me that if you have this rigid set of rules for turning multipliers into descriptions, they could be done programmatically instead of needing to be hardcoded.

2021-07-03 16:14 UTC, Kwazygloo commented
> It seems to me that if you have this rigid set of rules for turning multipliers into descriptions, they could be done programmatically instead of needing to be hardcoded.

Makes sense, but I already did the work.

2021-07-06 08:42 UTC, danielyxie requested changes

2021-07-06 08:42 UTC, danielyxie commented on src/Augmentation/AugmentationHelpers.jsx
> +             "Each level increases all multipliers by 1%.",
I would keep the part about it being possible for this Augmentation to be leveled up infinitely, as that is important information

2021-07-06 08:42 UTC, danielyxie commented on src/Augmentation/AugmentationHelpers.jsx
> +             "making the user more resilient as well as stealthy.<br><br>" ++
Extra plus sign at the end here

2021-07-06 08:42 UTC, danielyxie commented on src/Augmentation/AugmentationHelpers.jsx
> +                 "Increases Bladeburner Stamina by 10%.",
I'd add the word "max" back in here to be clear: `Bladeburner max stamina`. Same for all of the others

2021-07-06 08:42 UTC, danielyxie commented on src/Augmentation/AugmentationHelpers.jsx
> +                 "Increases Bladeburner Stamina gain by 5%.<br>",
We don't need this `<br>` at the end here

2021-08-15 06:04 UTC, hydroflame commented
These changes were included in some other form.

2021-08-15 06:04 UTC, closed without merging