Adding support for ctrl + arrow key navigation around open files in script-editor
danielyxie/bitburner pull request #2144
Opened 2021-12-23 00:56 UTC by PhilipArmstead

This listens for the keyup event instead of keypress or keydown because, I believe, Monaco is swallowing those events when pressing buttons that don't enter printable characters

2021-12-23 02:11 UTC, aaronransley commented
@PhilipArmstead I use ctrl+arrows to jump to word + special character stops. Would it be possible to use alt+arrows for tab switching instead? It seems those are currently unbound by Monaco.

2021-12-23 06:51 UTC, Hedrauta approved these changes
👍  ... it does even save the line and row i was in...

2021-12-23 06:53 UTC, Hedrauta commented
> @PhilipArmstead I use ctrl+arrows to jump to word + special character stops. Would it be possible to use alt+arrows for tab switching instead? It seems those are currently unbound by Monaco.

oh.... 🤔  never using this feature, bc i do program my scripts in vscode 😆

2021-12-23 07:04 UTC, Hedrauta requested changes
🤔 rethinking the approval and maybe just add Alt as additional Button... so Ctrl + ArrowLeft/Right can still be used to jump in the line 😉

2021-12-23 10:58 UTC, PhilipArmstead commented
I've added support for the Alt key too but that's not going to work very well in browsers (it will navigate forwards/backwards through history if available; at least Firefox does.)

2021-12-23 14:16 UTC, Hedrauta commented on src/ScriptEditor/ui/ScriptEditorRoot.tsx
> +      if ((event.ctrlKey || event.metaKey || event.altKey) && ['ArrowLeft', 'ArrowRight'].includes(event.key)) {
i meant  (Ctrl/Cmd) + Alt + arrowkey
```suggestion
      if (((event.ctrlKey || event.metaKey) && event.altKey) && ['ArrowLeft', 'ArrowRight'].includes(event.key)) {
```
ps: tested.... works great ;)

2021-12-23 18:36 UTC, Hedrauta commented
How it looks:

![gif (6)](https://user-images.githubusercontent.com/20142298/147279849-f47619e8-bf22-4776-9b2b-adc0a32397aa.gif)

2021-12-23 19:09 UTC, Hedrauta approved these changes

2021-12-27 02:31 UTC, apixdae commented
It may be too late to add this to the discussion, but the standard keyboard shortcut for switching tabs in a web browser, VSCode, etc is `Ctrl+Tab` to move forward and `Ctrl+Shift+Tab` to move backward (although VSCode handles it slightly differently, moving between tabs based on which were most recently visited, as opposed to position on the tab bar). It would be useful to be able to use the common shortcuts to switch tabs as opposed to new ones like `Ctrl+Alt+Left/Right`.

2021-12-27 14:05 UTC, Hedrauta commented
That may work for the steam version


But there are still people on the domain  one, which would interfere with the Browser's shortcut

2022-01-08 19:40 UTC, hydroflame commented
That's kindof the problem. Whatever shortcut we use will cause issues for one OS or another :\

2022-01-08 19:40 UTC, closed without merging