MISC: FIX #2205 It is no longer possible to get into debt by going to the gym or taking a class.
danielyxie/bitburner pull request #2949
Opened 2022-02-10 15:19 UTC by phyzical

* taking courses and going to gym without money
* logic to cancel work when out of money

closes #2205
closes #3515 

![Animation4](https://user-images.githubusercontent.com/5182053/153438147-07d4b0e7-b505-4373-8b95-0cb2a626d712.gif)

2022-02-11 11:49 UTC, pigalot commented
Have you added checks to the api and sleeves?

2022-02-11 12:12 UTC, phyzical commented
api yes i think you mean singularity correct?
sleeves no i have very little exp with them yet. 
but i will take a crack at that also, just for my understanding  reading the description of the docs sleeves are just "multiple versions of yourself" 
so basically just another version of ui functions that that have another entry point to most parts of the game?

2022-02-12 04:54 UTC, phyzical commented
ah damn good call sleeves is still able to go into -ve will fix now

2022-02-13 01:15 UTC, alainbryden commented
I'm so sorry for the effort you put in my dude, but this one is actually by design.

There's a steam achievement "Massive debt" - "Be $1b in debt.", and the intended way to earn this is by studying with little-to-no income.

If not for that, I would have thought this to be a change for the better.

Perhaps a way to salvage the PR is to indeed forbid working out at the gym (student debt is a real thing, but no one gives out a loan for working out at the gym) - and the same should probably apply to sleeves. Hydro will have the final call though, he might not be in favour of either.

2022-02-13 01:16 UTC, alainbryden requested changes
I'm so sorry for the effort you put in my dude, but this one is actually by design.

There's a steam achievement "Massive debt" - "Be $1b in debt.", and the intended way to earn this is by studying with little-to-no income.

If not for that, I would have thought this to be a change for the better.

Perhaps a way to salvage the PR is to indeed forbid working out at the gym (student debt is a real thing, but no one gives out a loan for working out at the gym) - and the same should probably apply to sleeves. Hydro will have the final call though, he might not be in favour of either.

2022-02-13 01:51 UTC, phyzical commented
all good issue, do we know how this related the issue that was left in the bug list?

2022-02-13 01:54 UTC, phyzical commented
guess i just assumed based on this it was all good 😆 

![image](https://user-images.githubusercontent.com/5182053/153734946-e06d1543-f81c-487a-a6ad-85074ce41f8d.png)

2022-02-13 02:40 UTC, alainbryden commented
I hadn't seen that comment so this may actually stick.

In that case, we might just want to make sure there's an alternate route to that achievement? (Should be some way that require exploits, or else it should probably be converted to an SF-1 achievement)

2022-02-13 05:10 UTC, phyzical commented
yep i agree,
 tbh hydro may have just given in and his opinion might  change once hes back.
can just sit till then

2022-03-02 02:51 UTC, illusori commented
There's other in-game ways to get that achievement, although personally I do like the social commentary on student debt.

<details><summary>Spoilers</summary>Short selling on the stock market is the quickest way to get massively in debt.</details>

2022-03-11 09:46 UTC, phyzical commented on src/ui/WorkInProgressRoot.tsx
> +    if (player.className != CONSTANTS.ClassStudyComputerScience && player.workType == CONSTANTS.WorkTypeStudyClass && player.money <= 0) {
hmm after making more prs to the codebase i think doing this here may be a mistake....

2022-04-06 23:34 UTC, hydroflame commented
PR made before mega fmt

run `npm run format` and push to (probably) fix merge conflicts.

2022-04-13 12:39 UTC, alainbryden commented
A lot of players are enjoying strategies around going in to debt with gym/studies, so I propose that in order to not have this PR get anybody angry:
- Add a new setting to the options menu "overdraft protection" that defaults to true. When "overdraft protection" is enabled, the new code in this PR prevents the player from going into the negative and forcibly leaves the gym/studies.
- If "overdraft protection" is disabled by the user, the current behaviour continues.

2022-04-13 13:10 UTC, phyzical commented
happy to add a setting if we feel its needed but imo it just forces the user to adjust their scripts accordingly i.e instead of relying on free money you commit some crimes for a bit then switch back to training

2022-04-20 01:12 UTC, taralx commented
Am I reading this correctly? It looks like you can still go into debt by 1 tick.

2022-04-20 13:36 UTC, phyzical commented
yeah you would probably end up going into a little bit of debt, i could enforce 0, but that could conflict anything else that could cause debt in the same tick

2022-04-20 17:17 UTC, taralx commented
It's an improvement over infinite debt.

2022-04-21 00:15 UTC, apdjz commented
Sorry for the double post. I thought I did a search for the issue.

2022-04-21 04:26 UTC, phyzical commented
@apdjz no need to say sorry :) double is better than none

2022-07-21 06:39 UTC, hydroflame commented
While this issue is still current, it massively conflict with the new work system so I'm going to close.

2022-07-21 06:39 UTC, closed without merging