Fix unique ip generation
danielyxie/bitburner pull request #3129
Opened 2022-03-12 17:35 UTC by InDieTasten

The previous implementation had a bug in it, where the generated IP
wouldn't be unique, if the generated IP wouldn't be unique two times in
a row.

Conducted tests:
Quick check in the game:
![image](https://user-images.githubusercontent.com/7047377/158028466-0e9c5480-7031-412c-9aef-1033e2342800.png)

Test suite result:
![image](https://user-images.githubusercontent.com/7047377/158028441-050085ce-ad0f-49c4-8df0-d4d33d1cc353.png)

2022-03-12 23:46 UTC, phyzical approved these changes
LGTM, one thing though if for whatever reason the issue was the randomization the game would get stuck in an infinite loop, maybe add a max of like 15-20 tries?

the randomization looks to be this
https://github.com/danielyxie/bitburner/blob/dev/src/utils/helpers/getRandomInt.ts#L10

2022-03-12 23:51 UTC, ApamNapat requested changes

2022-03-12 23:51 UTC, ApamNapat commented on src/Server/AllServers.ts
> +  let ip: string;
```
  let ip = createRandomIp();
  // Repeat generating ip, until unique one is found
  while (ipExists(ip)) {
    ip = createRandomIp();
  }
```
No need to use a quite rare `do...while` when a more typical loop would suffice

2022-03-12 23:54 UTC, ApamNapat commented
> LGTM, one thing though if for whatever reason the issue was the randomization the game would get stuck in an infinite loop, maybe add a max of like 15-20 tries?
> 
> the randomization looks to be this https://github.com/danielyxie/bitburner/blob/dev/src/utils/helpers/getRandomInt.ts#L10

`getRandomInt` is used all over the project, the whole game would break if it stopped working in such a simple case, this is too much caution IMHO

2022-03-12 23:56 UTC, phyzical commented
just to be clear im talking about the while loop generating the random ip address,

 not changing getRandomInt. just meant thats where its randomness resides

2022-03-13 13:31 UTC, InDieTasten commented
@phyzical I thought about it, but limiting the loop would add more complexity for a system (server IPs), that isn't really widely used.

The bug of non-unique ip being assigned was already rare, because it required the createRandomIp function to produce a duplicate twice in a row. With every iteration of the loop, the overall chance of continuing gets even slimmer, especially since we have such a large IP space with only a couple dozen servers being assigned an IP.

As for using a while loop instead of do...while, I can post an update in a couple hours.

2022-03-16 18:53 UTC, merged